name: Shopware
description: |
  Shopware Stack with Database and PHPMyAdmin
version: 0.0.1
category: wsk
maintainer: pw@web-service-kaupa.de
license: # The license
projectURL: # A URL related to the catalog entry
